### ISSUE TITLE
questions about  StructuredAttention.py

### ISSUE THREAD

**Issue by VinnyHu** [vidhishanair/structured-text-representations#3]
Hi thanks for your great implementation code！
I have some confusions about StructuredAttention.py

I don‘t know the function of this code below ：

        if(self.bidirectional):
            input = input.view(batch_size, token_size, 2, dim_size//2)
            sem_v = torch.cat((input[:,:,0,:self.sem_dim_size//2],input[:,:,1,:self.sem_dim_size//2]),2)
            str_v = torch.cat((input[:,:,0,self.sem_dim_size//2:],input[:,:,1,self.sem_dim_size//2:]),2)
        else:
            sem_v = input[:,:,:self.sem_dim_size]
            str_v = input[:,:,self.sem_dim_size:]

especially  self.bidirectional， what does it means？

looking forward to your reply！

thanks！

**Comment by vidhishanair** [comment]
This is a flag for Bidirectional LSTM v/s Single Directional LSTM.
